<a href="https://colab.research.google.com/github/1234567890qqqqqq/bsc_dpdm22/blob/main/Performance_Evaluation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn import datasets

iris_data = datasets.load_iris()

In [2]:
X = iris_data['data']

y = iris_data['target']

In [3]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, KFold

In [4]:
model = DecisionTreeClassifier()

# Define the k-fold cross validation
kf = KFold(n_splits=10, shuffle=True, random_state=42)

# Train and evaluate the model using 10-fold cross validation
scores = cross_val_score(model, X, y, cv=kf)

# Print the average accuracy and standard deviation across all folds
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.94 (+/- 0.11)

In [5]:
model = DecisionTreeClassifier(max_depth=2)

# Define the k-fold cross validation
kf = KFold(n_splits=10, shuffle=True, random_state=42)

# Train and evaluate the model using 10-fold cross validation
scores = cross_val_score(model, X, y, cv=kf)

# Print the average accuracy and standard deviation across all folds
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.95 (+/- 0.12)

In [6]:
from sklearn.model_selection import LeaveOneOut

In [7]:
model = DecisionTreeClassifier(max_depth=2)

# Define the k-fold cross validation
LOO = LeaveOneOut()

# Train and evaluate the model using 10-fold cross validation
scores = cross_val_score(model, X, y, cv=LOO)

# Print the average accuracy and standard deviation across all folds
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.95 (+/- 0.42)

In [8]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

transform numpy array to dataframe

In [9]:
import pandas as pd

In [10]:
columns = iris_data['feature_names']
X_df = pd.DataFrame(X, columns=columns)

In [11]:
X_df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [12]:
X_df['label']=y

In [13]:
X_df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [14]:
shuffled_df = X_df.sample(frac=1,random_state=6)
shuffled_df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
4,5.0,3.6,1.4,0.2,0
116,6.5,3.0,5.5,1.8,2
2,4.7,3.2,1.3,0.2,0
23,5.1,3.3,1.7,0.5,0
123,6.3,2.7,4.9,1.8,2
...,...,...,...,...,...
148,6.2,3.4,5.4,2.3,2
79,5.7,2.6,3.5,1.0,1
109,7.2,3.6,6.1,2.5,2
106,4.9,2.5,4.5,1.7,2
138,6.0,3.0,4.8,1.8,2

In [15]:
shuffled_df['fold']=15*[1,2,3,4,5,6,7,8,9,10]

In [16]:
shuffled_df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label,fold
4,5.0,3.6,1.4,0.2,0,1
116,6.5,3.0,5.5,1.8,2,2
2,4.7,3.2,1.3,0.2,0,3
23,5.1,3.3,1.7,0.5,0,4
123,6.3,2.7,4.9,1.8,2,5
...,...,...,...,...,...,...
148,6.2,3.4,5.4,2.3,2,6
79,5.7,2.6,3.5,1.0,1,7
109,7.2,3.6,6.1,2.5,2,8
106,4.9,2.5,4.5,1.7,2,9
138,6.0,3.0,4.8,1.8,2,10

# HW6 วนลูปทำ 10-fold cross validation

In [17]:
X = shuffled_df.drop(['label','fold'], axis=1)
X

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
4                  5.0               3.6                1.4               0.2
116                6.5               3.0                5.5               1.8
2                  4.7               3.2                1.3               0.2
23                 5.1               3.3                1.7               0.5
123                6.3               2.7                4.9               1.8
..                 ...               ...                ...               ...
148                6.2               3.4                5.4               2.3
79                 5.7               2.6                3.5               1.0
109                7.2               3.6                6.1               2.5
106                4.9               2.5                4.5               1.7
138                6.0               3.0                4.8               1.8

[150 rows x 4 columns]

In [18]:
X_df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [19]:
import pandas as pd
from sklearn.model_selection import KFold
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold, cross_val_score
from sklearn.tree import DecisionTreeClassifier

# Split the data into features and target
X = X_df.drop('label', axis=1)
X_df['label'] = y
y = X_df['label']

# Set the number of folds and initialize a new column to store the fold number
num_folds = 10
X['fold'] = -1

# Create a KFold object and use it to assign fold numbers to each row
kf = KFold(n_splits=num_folds, shuffle=True, random_state=42)
for fold, (train_index, test_index) in enumerate(kf.split(X)):
    X.loc[test_index, 'fold'] = fold

In [20]:
# Initialize a list to store the model's scores
scores = []

# Loop through each fold and fit a linear regression model
for fold in range(num_folds):
    # Get the training and test sets for this fold
    X_train = X[X['fold'] != fold].drop('fold', axis=1)
    y_train = y[X['fold'] != fold]
    X_test = X[X['fold'] == fold].drop('fold', axis=1)
    y_test = y[X['fold'] == fold]
    
    # Fit a linear regression model to the training data
    model = DecisionTreeClassifier(max_depth=2)
    model.fit(X_train, y_train)
    
    # Evaluate the model on the test data
    score = cross_val_score(model, X_test, y_test, cv=kf)
    # Append the score to the list of scores
    scores.append(score)

# Compute the average score across all folds
avg_score = sum(scores) / len(scores)
print(f'Average score: {avg_score}');
#average can changes all time???

Average score: [0.85 0.85 0.8  0.85 1.   0.9  1.   0.8  0.8  0.8 ]

In [21]:
# Perform cross validation and compute the accuracy for each fold
fold_accuracies = cross_val_score(model, X, y, cv=kf)

# Compute the mean accuracy across all folds
mean_accuracy = fold_accuracies.mean()

# Print the accuracy for each fold and the mean accuracy
for fold, accuracy in enumerate(fold_accuracies):
    print(f'Fold {fold + 1} accuracy: {accuracy:.3f}')
print(f'Mean accuracy: {mean_accuracy:.3f}')

Fold 1 accuracy: 1.000
Fold 2 accuracy: 1.000
Fold 3 accuracy: 1.000
Fold 4 accuracy: 0.933
Fold 5 accuracy: 1.000
Fold 6 accuracy: 0.867
Fold 7 accuracy: 0.867
Fold 8 accuracy: 1.000
Fold 9 accuracy: 0.933
Fold 10 accuracy: 0.867
Mean accuracy: 0.947

##เพื่อนทำถูก90%

In [22]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, KFold
# Load the iris dataset (โหลดชุดข้อมูล iris)
iris = load_iris()
X = iris.data #แยกข้อมูล iris.data เป็น Input โดยใช้เป็นตัวแปร X
y = iris.target #แยกข้อมูล iris.target เป็น Output โดยใช้เป็นตัวแปร y

# Create a decision tree classifier (สร้างต้นไม้ตัดสินใจ)
clf = DecisionTreeClassifier()

# Create a 10-fold cross-validation object (สร้างการวนลูป 10 fold)
kf = KFold(n_splits=10) 

# Loop through each fold and train/evaluate the decision tree วนซ้ำแต่ละส่วนและประเมินแผนผังการตัดสินใจ
for train_index, test_index in kf.split(X):
    # Get the training and testing data for this fold #รับข้อมูล training and testing 
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    # Train the decision tree on the training data for this fold ตัดสินใจเกี่ยวกับข้อมูล training 
    clf.fit(X_train, y_train)
    
    # Evaluate the decision tree on the testing data for this fold ประเมินแผนผังการตัดสินใจของ training data สำหรับ  fold
    score = clf.score(X_test, y_test)
    
    # Print the accuracy for this fold #แสดงค่าความแม่นยำ
    print("Accuracy: %0.2f" % score)

Accuracy: 1.00
Accuracy: 1.00
Accuracy: 1.00
Accuracy: 1.00
Accuracy: 0.93
Accuracy: 0.87
Accuracy: 1.00
Accuracy: 0.87
Accuracy: 0.87
Accuracy: 1.00

#อาจารย์ เฉลย

In [23]:
from sklearn.metrics import accuracy_score
import numpy as np

In [24]:
test_fold = 1

test_data = shuffled_df[shuffled_df['fold']==test_fold]
training_data = shuffled_df[shuffled_df['fold']!=test_fold]

In [25]:
X_test = test_data.iloc[:,:-2]
y_test = test_data.iloc[:,-2]
X_train = training_data.iloc[:,:-2]
y_train = training_data.iloc[:,-2]

In [26]:
model = DecisionTreeClassifier(max_depth=2)

model.fit(X_train,y_train)

y_predict = model.predict(X_test)

In [27]:
acc = accuracy_score(y_test,y_predict)
print(f'accuracy of fold {test_fold} = {acc}')

accuracy of fold 1 = 0.8666666666666667

In [28]:
acc_fold=[]
for test_fold in range(1,11):
    test_data = shuffled_df[shuffled_df['fold']==test_fold]
    training_data = shuffled_df[shuffled_df['fold']!=test_fold]

    X_test = test_data.iloc[:,:-2]
    y_test = test_data.iloc[:,-2]
    X_train = training_data.iloc[:,:-2]
    y_train = training_data.iloc[:,-2]

    model = DecisionTreeClassifier(max_depth=2)
    model.fit(X_train,y_train)
    y_predict = model.predict(X_test)

    acc = accuracy_score(y_test,y_predict)
    print(f'accuracy of fold {test_fold} = {acc}')
    acc_fold.append(acc)

print(f'\naverage accuracy = {np.mean(acc_fold)}')

accuracy of fold 1 = 0.8666666666666667
accuracy of fold 2 = 1.0
accuracy of fold 3 = 0.9333333333333333
accuracy of fold 4 = 1.0
accuracy of fold 5 = 0.9333333333333333
accuracy of fold 6 = 0.9333333333333333
accuracy of fold 7 = 0.9333333333333333
accuracy of fold 8 = 1.0
accuracy of fold 9 = 0.8666666666666667
accuracy of fold 10 = 0.9333333333333333

average accuracy = 0.9400000000000001

#add Precision & Recall from ChatGPT

In [29]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, KFold
from sklearn.metrics import precision_score, recall_score

# Load the iris dataset
iris = load_iris()

# Define the decision tree model
model = DecisionTreeClassifier()

# Define the k-fold cross validation
kf = KFold(n_splits=10, shuffle=True, random_state=42)

# Train and evaluate the model using 10-fold cross validation
precision_scores = []
recall_scores = []
for train_idx, test_idx in kf.split(iris.data, iris.target):
    # Get the training and testing data for this fold
    X_train, y_train = iris.data[train_idx], iris.target[train_idx]
    X_test, y_test = iris.data[test_idx], iris.target[test_idx]

    # Train the model on the training data for this fold
    model.fit(X_train, y_train)

    # Predict the labels for the testing data for this fold
    y_pred = model.predict(X_test)

    # Calculate the precision and recall for this fold
    precision = precision_score(y_test, y_pred, average='macro')
    recall = recall_score(y_test, y_pred, average='macro')

    # Add the precision and recall scores to the lists for all folds
    precision_scores.append(precision)
    recall_scores.append(recall)

# Print the average precision and recall scores across all folds
print("Average precision score: %0.2f" % (sum(precision_scores) / len(precision_scores)))
print("Average recall score: %0.2f" % (sum(recall_scores) / len(recall_scores)))

Average precision score: 0.96
Average recall score: 0.96